let {generateListOfUsers} = require("../src/actions/retrieveUsers");

const chai = require("chai");
const should = chai.should();

let users = [
    { "firstName": "", "lastName": "", "email": "", "phone": "", "userId":0 },
    {
      "firstName": "Anca",
      "lastName": "Huiban",
      "email": "ancahuiban@gmail.com",
      "phone": "0734454323",
      "userId": 1
    },
    {
      "firstName": "Gelutu",
      "lastName": "Hardian",
      "email": "hadrianemepror@gmail.com",
      "phone": "0734453213",
      "userId": 2
    },
    {
      "firstName": "Joe",
      "lastName": "Doe",
      "email": "joedoe@gmail.com",
      "phone": "0734457723",
      "userId": 3
    },
    {
      "firstName": "Giussepe",
      "lastName": "Verdi",
      "email": "clasifimofo@gmail.com",
      "phone": "0737754323",
      "userId": 4
    }
  ];
  
describe("We're testing the validation of generateListOfUsers function", ()=>{
    it('Testing if the results generated by our function are the same as expected', done =>{

        let expectedResults = [{
            "firstName": "Gelutu",
            "lastName": "Hardian",
            "email": "hadrianemepror@gmail.com",
            "phone": "0734453213",
            "userId": 2
          },
          {
            "firstName": "Joe",
            "lastName": "Doe",
            "email": "joedoe@gmail.com",
            "phone": "0734457723",
            "userId": 3
          },];
        let result = generateListOfUsers(':2,3');
        console.log(result);
        chai.expect(expectedResults).to.deep.equal(result);
        done();
    });
});
